# Generated by Django 4.1.4 on 2022-12-10 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech_marathon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(default=999, max_length=30),
            preserve_default=False,
        ),
    ]
