# Generated by Django 4.1.4 on 2022-12-10 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech_marathon', '0002_user_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ManyToManyField(related_name='book', to='tech_marathon.category'),
        ),
        migrations.DeleteModel(
            name='BookCategory',
        ),
    ]
