# Generated by Django 4.1.4 on 2022-12-11 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tech_marathon', '0003_rename_user_id_book_user_book_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.ManyToManyField(null=True, related_name='book', to='tech_marathon.category'),
        ),
        migrations.AlterField(
            model_name='book',
            name='end_date',
            field=models.DateTimeField(null=True, verbose_name='finished reading date'),
        ),
        migrations.AlterField(
            model_name='book',
            name='memo',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='goal',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
